# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Model European Union Sofia
# Description of the Site
description: Simulation of European Politics
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: EU, Europe, Sofia, Education
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.pixabay.com/photo/2017/04/27/07/02/church-2264661_960_720.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
github_username:
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name:
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pharetra velit, dapibus bibendum ex. Maecenas vitae laoreet mauris, ac luctus metus. Aliquam luctus velit vel ipsum feugiat, vel venenatis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
