# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Levi Keay
# Description of the Site
description: Projects and interests
# URL of Image of the Site
site-image: https://media.istockphoto.com/photos/very-closeup-view-of-amazing-domestic-pet-in-mirror-round-fashion-is-picture-id1281804798?b=1&k=20&m=1281804798&s=170667a&w=0&h=HIWbeaP_cQSngCz7l9t3xwyE2eyzVgIy3K6xIqPhJQA=
# Keywords of the Site
site-keywords: Levi Keay, Resume, Physics, Remote Sensing
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://media.istockphoto.com/photos/very-closeup-view-of-amazing-domestic-pet-in-mirror-round-fashion-is-picture-id1281804798?b=1&k=20&m=1281804798&s=170667a&w=0&h=HIWbeaP_cQSngCz7l9t3xwyE2eyzVgIy3K6xIqPhJQA=

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Levi Keay
# URL for the Image of the Author
author-image: https://images.pexels.com/photos/3772623/pexels-photo-3772623.jpeg?cs=srgb&dl=pexels-andrea-piacquadio-3772623.jpg&fm=jpg
# 60 Words About the Author
author-about: Levi is a recent graduate of the University of British Columbia's physics program. His interests include imaging, acoustics, and programming.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: /

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
