# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://abinashgit005.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Abinash Mishra
# Description of the Site
description: DevOps Enthusiastic
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: DevOps, Blog, Portfolio, Abinash
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/mywebsitehomenew.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mishraabinash051@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: abinash051
github_username:  abinashgit005
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Abinash Mishra
# URL for the Image of the Author
author-image: /assets/images/WhatsApp.jpg
# 60 Words About the Author
author-about: DevOps Engineer
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://abinashmishra.in

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
